__title__ = "Iro"
__description__ = "Easy and powerful Colorizer for Python!"
__url__ = "https://github.com/nagataaaas/Iro"
__version_info__ = ("1", "0", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "nagata@nagata.pro"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2024 by Yamato Nagata"
